<a href="https://colab.research.google.com/github/gargiisc/mlc/blob/main/Experiment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**EXPERIMENT 5**<br>
**Aim:** To study and perform Multiple Linear Regression model.

 **Simple Linear Regression**, where a single Independent/Predictor(X) variable is used to model the response variable (Y). But there may be various cases in which the response variable is affected by more than one predictor variable; for such cases, the Multiple Linear Regression algorithm is used. Moreover, Multiple Linear Regression is an extension of Simple Linear regression as it takes more than one predictor variable to predict the response variable. We can define it as: <br>
**Definition:** Multiple Linear Regression is one of the important regression algorithms which models the linear relationship between a single dependent continuous variable and more than one independent variable. <br>
**Example**:<br>
Prediction of CO2 emission based on engine size and number of cylinders in a car. <br>
**Multiple Linear Regression** <br>
In Multiple Linear Regression, the target variable(Y) is a linear combination of multiple predictor variables x1, x2, x3, ...,xn. Since it is an enhancement of Simple Linear Regression, so the same is applied for the multiple linear regression equation, the equation becomes:
Implementation of Multiple Linear Regression model using Python:
To implement MLR using Python, we have below problem:
We have a dataset of 6 home prices. This dataset contains four main information: Area, Bedroom, Age & Price. To create a model that can easily determine which house has a maximum price, and which is the most affecting factor for the profit of a house.
Since we need to find the Profit, so it is the dependent variable, and the other three variables are independent variables.  
1. Data Pre-processing Steps
2. Fitting the MLR model to the training set
3. Predicting the result of the test set


In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
uploaded = files.upload()

Saving homeprice_new.csv to homeprice_new.csv


In [3]:
df = pd.read_csv('homeprice_new.csv')
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Data Preprocessing: Fill NA values with median value of a column

In [4]:
df.Bedrooms.median()

4.0

In [5]:
df.Bedrooms = df.Bedrooms.fillna(df.Bedrooms.median())
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Find X and Y

In [6]:
X = df.drop('Price', axis='columns')
X

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [7]:
Y = df.Price
Y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: Price, dtype: int64

### Fit Linear Regression Model

In [8]:
reg = linear_model.LinearRegression()
reg.fit(X,Y)

LinearRegression()

In [10]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [9]:
reg.intercept_

221323.00186540396

### Price of home with 3000 sqft area, 3 bedrooms, 40 years old

In [11]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

### Price of home with 2500 sqft area, 4 bedrooms, 5 years old

In [12]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

### Actual Price V/s Predicted Price

In [14]:
predicted_prices = reg.predict(X)
results_df = pd.DataFrame({'Actual Price': Y, 'Predicted Price': predicted_prices})
results_df

Actual Price  Predicted Price
0        550000    518217.632976
1        565000    602590.079374
2        610000    615307.414037
3        595000    597962.895832
4        760000    760663.426755
5        810000    795258.551027